# Generated by Django 3.2.13 on 2022-05-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comment_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_URL',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
